/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author piace
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        btnAnf = new javax.swing.JRadioButton();
        btnMj = new javax.swing.JRadioButton();
        btnEx = new javax.swing.JRadioButton();
        btnMeta = new javax.swing.JRadioButton();
        btnCo = new javax.swing.JRadioButton();
        btnHero = new javax.swing.JRadioButton();
        scrollAnfe = new javax.swing.JScrollPane();
        listAnfe = new javax.swing.JList<>();
        scrollMJ = new javax.swing.JScrollPane();
        listMJ = new javax.swing.JList<>();
        scrollEx = new javax.swing.JScrollPane();
        listEx = new javax.swing.JList<>();
        scrollMeta = new javax.swing.JScrollPane();
        listMeta = new javax.swing.JList<>();
        scrollCoca = new javax.swing.JScrollPane();
        listCoca = new javax.swing.JList<>();
        scrollHero = new javax.swing.JScrollPane();
        listHero = new javax.swing.JList<>();
        jSpinner1 = new javax.swing.JSpinner();
        btnDeleteLast = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGroup.add(btnAnf);
        btnAnf.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAnf.setText("Anfetamina");

        btnGroup.add(btnMj);
        btnMj.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMj.setText("Marihuana");

        btnGroup.add(btnEx);
        btnEx.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEx.setText("Extasis");

        btnGroup.add(btnMeta);
        btnMeta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMeta.setText("Meta Cristal");

        btnGroup.add(btnCo);
        btnCo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCo.setText("Cocaína");

        btnGroup.add(btnHero);
        btnHero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHero.setText("Heroína");

        listAnfe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listAnfeMouseClicked(evt);
            }
        });
        scrollAnfe.setViewportView(listAnfe);

        listMJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMJMouseClicked(evt);
            }
        });
        scrollMJ.setViewportView(listMJ);

        listEx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listExMouseClicked(evt);
            }
        });
        scrollEx.setViewportView(listEx);

        listMeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMetaMouseClicked(evt);
            }
        });
        scrollMeta.setViewportView(listMeta);

        listCoca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCocaMouseClicked(evt);
            }
        });
        scrollCoca.setViewportView(listCoca);

        listHero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listHeroMouseClicked(evt);
            }
        });
        scrollHero.setViewportView(listHero);

        jSpinner1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        btnDeleteLast.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDeleteLast.setText("DELETE THE LAST");
        btnDeleteLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLastActionPerformed(evt);
            }
        });

        btnOK.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnOK.setText("OK");

        btnClear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnClear.setText("CLEAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSpinner1)
                            .addComponent(btnAnf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(scrollAnfe, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(scrollMJ, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(0, 4, Short.MAX_VALUE))
                                    .addComponent(btnMj, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(scrollEx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(scrollMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(scrollCoca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(scrollHero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEx, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnHero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnOK)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteLast, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEx, scrollEx});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMj, scrollMJ});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEx)
                            .addComponent(btnMeta)
                            .addComponent(btnCo)
                            .addComponent(btnHero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scrollCoca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollMeta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollEx)
                            .addComponent(scrollHero, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollAnfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollMJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteLast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listAnfeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAnfeMouseClicked
        btnAnf.doClick();
    }//GEN-LAST:event_listAnfeMouseClicked

    private void listMJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMJMouseClicked
        btnMj.doClick();
    }//GEN-LAST:event_listMJMouseClicked

    private void listExMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listExMouseClicked
        btnEx.doClick();
    }//GEN-LAST:event_listExMouseClicked

    private void listMetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMetaMouseClicked
        btnMeta.doClick();
    }//GEN-LAST:event_listMetaMouseClicked

    private void listCocaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCocaMouseClicked
        btnCo.doClick();
    }//GEN-LAST:event_listCocaMouseClicked

    private void listHeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listHeroMouseClicked
        btnHero.doClick();
    }//GEN-LAST:event_listHeroMouseClicked

    private void btnDeleteLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteLastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAnf;
    private javax.swing.JButton btnClear;
    private javax.swing.JRadioButton btnCo;
    private javax.swing.JButton btnDeleteLast;
    private javax.swing.JRadioButton btnEx;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JRadioButton btnHero;
    private javax.swing.JRadioButton btnMeta;
    private javax.swing.JRadioButton btnMj;
    private javax.swing.JButton btnOK;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JList<String> listAnfe;
    private javax.swing.JList<String> listCoca;
    private javax.swing.JList<String> listEx;
    private javax.swing.JList<String> listHero;
    private javax.swing.JList<String> listMJ;
    private javax.swing.JList<String> listMeta;
    private javax.swing.JScrollPane scrollAnfe;
    private javax.swing.JScrollPane scrollCoca;
    private javax.swing.JScrollPane scrollEx;
    private javax.swing.JScrollPane scrollHero;
    private javax.swing.JScrollPane scrollMJ;
    private javax.swing.JScrollPane scrollMeta;
    // End of variables declaration//GEN-END:variables
}
